
export let FORM_PROPUESTA_GRADO = {
    titulo: 'PropuestaGrado',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'PropuestaGrado',
    campos: [
    // {
    //     etiqueta: 'input',
    //     claseGrid: 'col-6',
    //     nombre: 'Id',
    //     label_i18n: 'id',
    //     placeholder_i18n: 'id',
    //     requerido: true,
    //     tipo: 'number',
    // },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Nombre',
        label_i18n: 'titulo_proyecto',
        placeholder_i18n: 'placeholder_titulo_proyecto',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'GrupoInvestigacion',
        label_i18n: 'grupo_investigacion',
        placeholder_i18n: 'placeholder_grupo_investigacion',
        requerido: false,
        tipo: 'GrupoInvestigacion',
        key: 'Nombre',
        oopciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'LineaInvestigacion',
        label_i18n: 'linea_investigacion',
        placeholder_i18n: 'placeholder_linea_investigacion',
        requerido: false,
        tipo: 'LineaInvestigacion',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'EnfasisProyecto',
        label_i18n: 'enfasis',
        placeholder_i18n: 'enfasis',
        requerido: false,
        tipo: 'Enfasis',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'TipoProyecto',
        label_i18n: 'tipoproyecto',
        placeholder_i18n: 'tipoproyecto',
        requerido: false,
        tipo: 'TipoProyecto',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'file',
        claseGrid: 'col-6',
        clase: 'form-control',
        nombre: 'Formatoproyecto',
        label_i18n: 'formatoproyecto',
        placeholder_i18n: 'formatoproyecto',
        requerido: false,
        tipo: 'pdf',
        tipoDocumento: 2,
        formatos: 'pdf',
        url: '',
        tamanoMaximo: 2,
    },
    {
        etiqueta: 'textarea',
        claseGrid: 'col-12',
        nombre: 'Resumen',
        label_i18n: 'resumen',
        placeholder_i18n: 'resumen',
        requerido: false,
        tipo: 'text',
    },
    ],
}
