
export let FORM_PROPUESTA_GRADO = {
    titulo: 'PropuestaGrado',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'PropuestaGrado',
    campos: [
    // {
    //     etiqueta: 'input',
    //     claseGrid: 'col-6',
    //     nombre: 'Id',
    //     label_i18n: 'id',
    //     placeholder_i18n: 'id',
    //     requerido: true,
    //     tipo: 'number',
    // },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Nombre',
        label_i18n: 'nombre',
        placeholder_i18n: 'nombre',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Grupoinvestigacion',
        label_i18n: 'grupoinvestigacion',
        placeholder_i18n: 'grupoinvestigacion',
        requerido: false,
        tipo: 'text', //tipo: 'EstadoAdmision',
        oopciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Lineainvestigacion',
        label_i18n: 'lineainvestigacion',
        placeholder_i18n: 'lineainvestigacion',
        requerido: false,
        tipo: 'text',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Duracion',
        label_i18n: 'duracion',
        placeholder_i18n: 'duracion',
        requerido: false,
        tipo: 'number',
    },
    // {
    //     etiqueta: 'input',
    //     claseGrid: 'col-6',
    //     nombre: 'UnidadTiempo',
    //     label_i18n: 'unidad_tiempo',
    //     placeholder_i18n: 'unidad_tiempo',
    //     requerido: true,
    //     enable: false,
    //     tipo: 'number',
    // },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Tipoproyecto',
        label_i18n: 'tipoproyecto',
        placeholder_i18n: 'tipoproyecto',
        requerido: false,
        tipo: 'text',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Lugarejecucion',
        label_i18n: 'lugarejecucion',
        placeholder_i18n: 'lugarejecucion',
        requerido: true,
        tipo: 'text',
        opciones: [],
    },
    {
        etiqueta: 'editor',
        claseGrid: 'col-12',
        nombre: 'Resumen',
        label_i18n: 'resumen',
        placeholder_i18n: 'resumen',
        requerido: false,
        tipo: 'text',
    },
    ],
}
