export let FORM_ARTICULO = {
    // titulo: 'Articulo',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Articulo',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Nombre',
            label_i18n: 'nombre',
            placeholder_i18n: 'nombre',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'Tipo',
            label_i18n: 'tipo_articulo',
            placeholder_i18n: 'tipo_articulo',
            requerido: true,
            tipo: 'TipoArticulo',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'Idioma',
            label_i18n: 'idioma_publicacion',
            placeholder_i18n: 'placeholder_idioma_publicacion',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Revista',
            label_i18n: 'revista',
            placeholder_i18n: 'revista',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'Ano',
            label_i18n: 'ano',
            placeholder_i18n: 'ano',
            requerido: true,
            tipo: 'number',
            minimo: 1970,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'Mes',
            label_i18n: 'mes',
            placeholder_i18n: 'mes',
            requerido: true,
            tipo: 'number',
            key: 'Nombre',
            relacion: false,
            opciones: [
                { Id: 1, Nombre: 'Enero' },
                { Id: 2, Nombre: 'Febrero' },
                { Id: 3, Nombre: 'Marzo' },
                { Id: 4, Nombre: 'Abril' },
                { Id: 5, Nombre: 'Mayo' },
                { Id: 6, Nombre: 'Junio' },
                { Id: 7, Nombre: 'Julio' },
                { Id: 8, Nombre: 'Agosto' },
                { Id: 9, Nombre: 'Septiembre|' },
                { Id: 10, Nombre: 'Octubre' },
                { Id: 11, Nombre: 'Noviembre' },
                { Id: 12, Nombre: 'Diciembre' },
            ],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-2 col-md-2 col-sm-12 col-xs-12',
            nombre: 'Volumen',
            label_i18n: 'volumen',
            placeholder_i18n: 'volumen',
            requerido: false,
            tipo: 'number',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-2 col-md-2 col-sm-12 col-xs-12',
            nombre: 'Fasciculo',
            label_i18n: 'fasciculo',
            placeholder_i18n: 'fasciculo',
            requerido: false,
            tipo: 'number',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-2 col-md-2 col-sm-12 col-xs-12',
            nombre: 'Serie',
            label_i18n: 'serie',
            placeholder_i18n: 'serie',
            requerido: false,
            tipo: 'number',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'Ubicacion',
            label_i18n: 'ubicacion',
            placeholder_i18n: 'ubicacion',
            requerido: true,
            tipo: 'Lugar',
            key: 'Nombre',
            relacion: false,
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'MedioDivulgacion',
            label_i18n: 'medio_divulgacion',
            placeholder_i18n: 'mediodi_vulgacion',
            requerido: true,
            tipo: 'MedioDivulgacion',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Url',
            label_i18n: 'url',
            placeholder_i18n: 'url',
            requerido: false,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Doi',
            label_i18n: 'doi',
            placeholder_i18n: 'doi',
            requerido: false,
            tipo: 'text',
        },
    ],
}
