export let FORM_LIBRO = {
    // titulo: 'Libro',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Libro',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'TituloLibro',
            label_i18n: 'titulo_libro',
            placeholder_i18n: 'titulo_libro',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'TipoPublicacion',
            label_i18n: 'tipo_publicacion',
            placeholder_i18n: 'tipo_publicacion',
            requerido: true,
            tipo: 'TipoPublicacionLibro',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'Ano',
            label_i18n: 'ano',
            placeholder_i18n: 'ano',
            requerido: true,
            tipo: 'number',
            minimo: 1970,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'Mes',
            label_i18n: 'mes',
            placeholder_i18n: 'mes',
            requerido: true,
            tipo: 'number',
            key: 'Nombre',
            relacion: false,
            opciones: [
                { Id: 1, Nombre: 'Enero' },
                { Id: 2, Nombre: 'Febrero' },
                { Id: 3, Nombre: 'Marzo' },
                { Id: 4, Nombre: 'Abril' },
                { Id: 5, Nombre: 'Mayo' },
                { Id: 6, Nombre: 'Junio' },
                { Id: 7, Nombre: 'Julio' },
                { Id: 8, Nombre: 'Agosto' },
                { Id: 9, Nombre: 'Septiembre|' },
                { Id: 10, Nombre: 'Octubre' },
                { Id: 11, Nombre: 'Noviembre' },
                { Id: 12, Nombre: 'Diciembre' },
            ],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'TituloCapitulo',
            label_i18n: 'titulo_capitulo',
            placeholder_i18n: 'titulo_capitulo',
            requerido: false,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Paginas',
            label_i18n: 'paginas',
            placeholder_i18n: 'paginas',
            requerido: true,
            tipo: 'number',
            minimo: 1,
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Isbn',
            label_i18n: 'isbn',
            placeholder_i18n: 'isbn',
            requerido: true,
            tipo: 'number',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Ubicacion',
            label_i18n: 'ubicacion',
            placeholder_i18n: 'ubicacion',
            requerido: true,
            tipo: 'Lugar',
            key: 'Nombre',
            relacion: false,
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'MedioDivulgacion',
            label_i18n: 'medio_divulgacion',
            placeholder_i18n: 'medio_divulgacion',
            requerido: true,
            tipo: 'MedioDivulgacion',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'MedioPublicacion',
            label_i18n: 'medio_publicacion',
            placeholder_i18n: 'medio_publicacion',
            requerido: true,
            tipo: 'MedioPublicacion',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Editorial',
            label_i18n: 'editorial',
            placeholder_i18n: 'editorial',
            requerido: true,
            tipo: 'text',
        },
    ],
}
